### ISSUE TITLE
There was an error loading the shapeE model

### ISSUE THREAD

**Issue by yangwenchengw** [liuff19/Sherpa3D#7]
Loading shapeE model...
Traceback (most recent call last):
  File "/root/autodl-tmp/Sherpa3D/train.py", line 782, in <module>
    init_shape = get_normalize_mesh_shapE(FLAGS.text, FLAGS.use_fine_tuned_shepE_model)
  File "/root/autodl-tmp/Sherpa3D/utils.py", line 51, in get_normalize_mesh_shapE
    model.load_state_dict(torch.load(os.path.join('load/shapE-finetuned/shapE_finetuned_with_825kdata.pth'), map_location=device
  File "/root/miniconda3/envs/Sherpa3D/lib/python3.9/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/Sherpa3D/lib/python3.9/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by yangwenchengw** [comment]
Because the command wget https://huggingface.co/datasets/tiange/Cap3D/blob/main/misc/our_finetuned_models/shapE_finetuned_with_330kdata.pth pulled the web page incorrectly
